services:
  alchemy_rest.fractal_manager:
    class: League\Fractal\Manager
    public: false

  alchemy_rest.transformer_registry:
    class: Alchemy\Rest\Response\TransformerRegistry

  alchemy_rest.array_transformer:
    class: Alchemy\Rest\Response\ArrayTransformer
    arguments:
      - @alchemy_rest.fractal_manager
      - @alchemy_rest.transformer_registry

  alchemy_rest.negotiator:
    class: Negotiation\Negotiator

  alchemy_rest.content_type_matcher:
    class: Alchemy\Rest\Request\ContentTypeMatcher
    arguments:
      - @alchemy_rest.negotiator

  alchemy_rest.exception_transformer:
    class: Alchemy\Rest\Response\ExceptionTransformer\DefaultExceptionTransformer
    public: false
    arguments:
      - false

  alchemy_rest.exception_listener:
    class: Alchemy\RestBundle\EventListener\ExceptionListener
    arguments:
      - @alchemy_rest.content_type_matcher
      - @alchemy_rest.exception_transformer
      - []

  alchemy_rest.date_parser:
    class: Alchemy\Rest\Request\DateParser\FormatDateParser
    public: false
    arguments:
      - ~
      - ~

  alchemy_rest.json_body_decode_listener:
    class: Alchemy\RestBundle\EventListener\DecodeJsonBodyRequestListener
    arguments:
      - @alchemy_rest.content_type_matcher
      - ~

  alchemy_rest.date_request_listener:
    class: Alchemy\RestBundle\EventListener\DateParamRequestListener
    arguments:
      - @alchemy_rest.date_parser

  alchemy_rest.paginate_options_factory:
    class: Alchemy\RestBundle\Rest\Request\PaginationOptionsFactory
    arguments:
      - ~
      - ~

  alchemy_rest.paginate_request_listener:
    class: Alchemy\RestBundle\EventListener\PaginationParamRequestListener
    arguments:
      - @alchemy_rest.paginate_options_factory

  alchemy_rest.sort_options_factory:
    class: Alchemy\RestBundle\Rest\Request\SortOptionsFactory
    public: false
    arguments:
      - ~
      - ~
      - ~

  alchemy_rest.sort_request_listener:
    class: Alchemy\RestBundle\EventListener\SortParamRequestListener
    arguments:
      - @alchemy_rest.sort_options_factory

  alchemy_rest.response_listener:
    class: Alchemy\RestBundle\EventListener\ResponseListener
    arguments:
      - @alchemy_rest.array_transformer
      - @router
    tags:
      - { name: kernel.event_subscriber }
