services:
  alchemy_rest.fractal_manager:
    class: League\Fractal\Manager
    public: false

  alchemy_rest.array_transformer:
    class: Alchemy\Rest\Response\ArrayTransformer
    arguments:
      - @alchemy_rest.fractal_manager

  alchemy_rest.exception_transformer:
    class: Alchemy\Rest\Response\ExceptionTransformer\DefaultExceptionTransformer
    public: false

  alchemy_rest.exception_listener:
    class: Alchemy\RestBundle\EventListener\ExceptionListener
    arguments:
      - @alchemy_rest.exception_transformer
      - []

  alchemy_rest.date_parser:
    class: Alchemy\Rest\Request\DateParser\UtcDateParser
    public: false
    arguments:
      - ~
      - ~

  alchemy_rest.date_request_listener:
    class: Alchemy\RestBundle\EventListener\DateParamRequestListener
    arguments:
      - @alchemy_rest.date_parser

  alchemy_rest.sort_options_factory:
    class: Alchemy\RestBundle\Request\SortOptionsFactory
    public: false
    arguments:
      - ~
      - ~
      - ~

  alchemy_rest.sort_request_listener:
    class: Alchemy\RestBundle\EventListener\SortParamRequestListener
    arguments:
      - @alchemy_rest.sort_options_factory

  alchemy_rest.response_listener:
    class: Alchemy\RestBundle\EventListener\ResponseListener
    arguments:
      - @alchemy_rest.array_transformer
      - @router
    tags:
      - { name: kernel.event_subscriber }
